import { useCallback } from "react";
import { useTheme } from "./ThemeProvider";
import type { ThemeName } from "./ThemeProvider";

/**
 * Every user-facing string that carries a voice.
 *
 * Operator is the source of truth and is reproduced verbatim from 1.2.4 — it
 * is also the fallback: a theme only lists what it says differently, so any
 * key a theme omits reads exactly as Operator. That is deliberate for the
 * safety copy (toasts, errors, Delete Account, the Danger Zone): those must
 * not change with the look, so they live in Operator and are never overridden.
 *
 * A null value means "render nothing" — Bento drops the watermarks entirely.
 *
 * Placeholders are {name} and are filled by t(key, vars).
 */
const operator = {
  // ── Header, navigation, shell ──────────────────────────────────────────
  "header.greeting": "Operator // {handle}",
  "header.sub": null as string | null,
  "stats.streak": null as string | null,
  "stats.tasks": null as string | null,
  "stats.blocks": null as string | null,
  "dashboard.title": "Cockpit Dashboard",
  "plan.title": "Strategic Planner",
  "pack.title": "The Pack",
  "blocks.title": "System Protocols",
  "uptime.label": "Uptime today",
  "uptime.unit": "MIN",
  "signout": "Sign Out",
  "offline.pill": "OFFLINE — WORKING LOCALLY",
  "session.active": "Active Session",
  "session.untitled": "Untethered",
  "nav.home": "Cockpit",
  "nav.plan": "Planner",
  "nav.pack": "The Pack",
  "nav.blocks": "Protocols",

  // ── Dashboard: mission ─────────────────────────────────────────────────
  "mission.label": "Strategic Mission",
  "mission.placeholder": "DEFINE CORE TARGET",

  // ── Dashboard: intentions / tasks ──────────────────────────────────────
  "todo.label": "Current Intentions",
  "todo.count": "{done}/{total} SECURE",
  "todo.placeholder": "Add auxiliary intention...",
  "todo.add": "LOG",
  "todo.empty": "No Intentions Logged",

  // ── Dashboard: session ─────────────────────────────────────────────────
  "session.label": "Telemetry Initialization",
  "session.running": "Session Active",
  "session.target": "Core Target // {task}",
  "session.untitledTarget": "Untitled",
  "session.sub": null as string | null,
  "session.start": "ENGAGE PROTOCOLS",
  "session.endsAt": "Ends at {time}",
  "preset.25": "Sprint",
  "preset.45": "Flow",
  "preset.60": "Deep",
  "preset.90": "Lock",
  "preset.2": "Micro",

  // ── Dashboard: streak ──────────────────────────────────────────────────
  "streak.label": "OPERATOR STREAK",
  "streak.empty": "0 — START TODAY",
  "streak.unit": "Day Streak",
  "streak.avg": "AVG SESSION",
  "streak.best": "BEST DAY",
  "streak.minUnit": "MIN",
  "streak.bestEver": "BEST",
  "streak.daysUnit": "DAYS",
  "history.title": "Operator Telemetry // 30-Day History",
  "history.total": "Total Locked In",

  // ── The Pack ───────────────────────────────────────────────────────────
  "pack.add": "Add Operator",
  "pack.placeholder": "Handle...",
  "pack.online": "Active Operators // Live Status",
  "pack.offline": "Offline Operators",
  "pack.leaderboard": "The Weekly Arena // Leaderboard",
  "pack.refresh": "Refresh Ranks",
  "pack.empty": "No Records Found",
  "pack.emptyHint": '"THE BOARD IS CLEAR. BE THE FIRST."',
  "pack.unknown": "Unknown Operator",
  "pack.hours": "HRS",

  // ── Protocols / blocks ─────────────────────────────────────────────────
  "blocks.identity": "Operator Identity",
  "blocks.telemetry": "Session Telemetry",
  "blocks.uptime": "Operator Uptime",
  "blocks.boot": "Boot Initialization",
  "blocks.autostart": "LAUNCH ON STARTUP",
  "blocks.autostartSub":
    "Lock-In opens when your PC starts so uptime tracking begins automatically",
  "blocks.web": "Web Blocker Registry",
  "blocks.sites": "BLOCKED SITES",
  "blocks.default": "// DEFAULT",
  "blocks.custom": "// CUSTOM",
  "blocks.none": "NO CUSTOM BLOCKS ADDED",
  "blocks.remove": "REMOVE",
  "blocks.perm": "PERM",
  "blocks.session": "SESSION",
  "blocks.addSite": "+ ADD",
  "blocks.sitePlaceholder": "e.g. twitch.tv",
  "blocks.apps": "Restricted Registry",
  "blocks.appPlaceholder": "e.g. discord.exe",
  "blocks.drop": "Drag & Drop .exe files here",
  "blocks.browse": "Choose from Running Apps",
  "blocks.clear": "Registry Clear",

  // ── Planner ────────────────────────────────────────────────────────────
  "plan.calendar": "// GOOGLE CALENDAR SYNC",
  "plan.schedule": "YOUR SCHEDULE",
  "plan.disconnect": "DISCONNECT",
  "plan.connect": "Connect Calendar",
  "plan.empty": "Empty",
  "plan.logPlaceholder": "Log...",

  // ── Login ──────────────────────────────────────────────────────────────
  "login.subtitle": "Establish secure link to cockpit.",
  "login.protocol": "Protocol: STATION_LOGIN",
  "login.email": "Comm Link (Email)",
  "login.password": "Security Clearance",
  "login.handle": "Operator Handle",
  "login.submit": "Engage Protocol",
  "login.register": "Confirm Registration",
  "login.toRegister": "First time arriving? Create Account",
  "login.toLogin": "Already documented? Login here",
  "login.forgot": "Forgot Access Key?",
  "login.encrypted": "Encrypted Layer",
  "login.protocolRegister": "Protocol: REGISTER_NEW_OPERATOR",
  "login.subtitleForgot": "Recovery sequence initiated.",
  "login.protocolForgot": "Protocol: RESET_ACCESS_KEY",
  "login.sendReset": "Send Reset Link",
  "login.submitting": "Syncing...",
  "login.sending": "Sending...",
  "handle.submitting": "Locking In...",
  "pack.syncing": "SYNCING...",
  "blocks.dropActive": "DROP TO REGISTER",
  "watermark.left": "FOCUS",
  "watermark.right": "GRIND",

  // ── Handle overlay ─────────────────────────────────────────────────────
  "handle.eyebrow": "// Operator Registration",
  "handle.title": "Choose Your Handle",
  "handle.sub": "This cannot be changed after confirmation.",
  "handle.submit": "Lock In Handle",

  // ── Appearance ─────────────────────────────────────────────────────────
  "theme.title": "Theme",
  "theme.sub": "Changes the look and the wording. Blocking works the same in every theme.",
} as const;

export type CopyKey = keyof typeof operator;
type Overrides = Partial<Record<CopyKey, string | null>>;

/** Lowercase, short, friendly. No jargon. */
const notebook: Overrides = {
  "header.greeting": "hi, {handle}",
  "dashboard.title": "Today",
  "plan.title": "plan",
  "pack.title": "friends",
  "blocks.title": "blocked stuff",
  "uptime.label": "focused today",
  "uptime.unit": "min",
  "signout": "sign out",
  "offline.pill": "offline — working locally",
  "session.active": "in a session",
  "session.untitled": "no label",
  "nav.home": "home",
  "nav.plan": "plan",
  "nav.pack": "friends",
  "nav.blocks": "blocks",
  "mission.label": "this week's big thing",
  "mission.placeholder": "what are you working toward?",
  "todo.label": "to-do",
  "todo.count": "{done} of {total} done",
  "todo.placeholder": "add something…",
  "todo.add": "add",
  "todo.empty": "nothing here yet",
  "session.label": "start a session",
  "session.running": "in progress",
  "session.target": "working on: {task}",
  "session.untitledTarget": "something",
  "session.start": "lock in",
  "session.endsAt": "ends at {time}",
  "preset.25": "quick",
  "preset.45": "flow",
  "preset.60": "deep",
  "preset.90": "all in",
  "preset.2": "micro",
  "streak.label": "streak",
  "streak.empty": "start one today",
  "streak.unit": "days",
  "streak.avg": "avg session",
  "streak.best": "best day",
  "streak.minUnit": "min",
  "streak.bestEver": "best",
  "streak.daysUnit": "days",
  "history.title": "the last 30 days",
  "history.total": "total focused",
  "pack.add": "add a friend",
  "pack.placeholder": "their handle…",
  "pack.online": "here now",
  "pack.offline": "away",
  "pack.leaderboard": "this week",
  "pack.refresh": "refresh",
  "pack.empty": "nobody's here yet",
  "pack.emptyHint": "add a friend to get started",
  "pack.unknown": "someone",
  "pack.hours": "hrs",
  "blocks.identity": "you",
  "blocks.telemetry": "your sessions",
  "blocks.uptime": "time today",
  "blocks.boot": "startup",
  "blocks.autostart": "open when my pc starts",
  "blocks.autostartSub": "so your time starts counting without you thinking about it",
  "blocks.web": "blocked sites",
  "blocks.sites": "sites",
  "blocks.default": "the usual",
  "blocks.custom": "yours",
  "blocks.none": "nothing added yet",
  "blocks.remove": "remove",
  "blocks.perm": "always",
  "blocks.session": "sessions only",
  "blocks.addSite": "add",
  "blocks.sitePlaceholder": "e.g. twitch.tv",
  "blocks.apps": "blocked apps",
  "blocks.appPlaceholder": "e.g. discord.exe",
  "blocks.drop": "drop an .exe here",
  "blocks.browse": "pick from what's open",
  "blocks.clear": "nothing blocked",
  "plan.calendar": "google calendar",
  "plan.schedule": "your day",
  "plan.disconnect": "disconnect",
  "plan.connect": "connect calendar",
  "plan.empty": "nothing yet",
  "plan.logPlaceholder": "jot something…",
  "login.subtitle": "welcome back.",
  "login.protocol": "sign in to keep going",
  "login.email": "email",
  "login.password": "password",
  "login.handle": "pick a handle",
  "login.submit": "sign in",
  "login.register": "create account",
  "login.toRegister": "new here? create an account",
  "login.toLogin": "already have one? sign in",
  "login.forgot": "forgot your password?",
  "login.encrypted": "encrypted",
  "login.protocolRegister": "let's get you set up",
  "login.subtitleForgot": "forgot it? happens.",
  "login.protocolForgot": "we'll email you a link",
  "login.sendReset": "send link",
  "login.submitting": "signing in...",
  "login.sending": "sending...",
  "handle.submitting": "saving...",
  "pack.syncing": "refreshing...",
  "blocks.dropActive": "drop them here",
  "watermark.left": "focus",
  "watermark.right": "go",
  "handle.eyebrow": "one more thing",
  "handle.title": "pick a handle",
  "handle.sub": "this is what friends will see. you can't change it later.",
  "handle.submit": "use this handle",
  "theme.title": "look",
};

/** Product-neutral sentence case. */
const bento: Overrides = {
  "header.greeting": "{handle} · {weekday}",
  "dashboard.title": "Dashboard",
  "plan.title": "Plan",
  "pack.title": "Friends",
  "blocks.title": "Blocks",
  "uptime.label": "Focused today",
  "uptime.unit": "min",
  "signout": "Sign out",
  "offline.pill": "Offline — working locally",
  "session.active": "Session running",
  "session.untitled": "Untitled",
  "nav.home": "Home",
  "nav.plan": "Plan",
  "nav.pack": "Friends",
  "nav.blocks": "Blocks",
  "mission.label": "This week's goal",
  "mission.placeholder": "What are you working toward?",
  "todo.label": "Tasks",
  "todo.count": "{done} / {total} done",
  "todo.placeholder": "Add a task",
  "todo.add": "Add task",
  "todo.empty": "No tasks yet",
  "session.label": "Focus",
  "session.running": "Focusing",
  "session.target": "{task}",
  "session.untitledTarget": "Untitled",
  "session.sub": "Blocks {apps} apps · {sites} sites",
  "session.start": "Start focus",
  "session.endsAt": "Ends at {time}",
  "preset.25": "Quick",
  "preset.45": "Flow",
  "preset.60": "Deep",
  "preset.90": "Lock",
  "preset.2": "Micro",
  "streak.label": "Streak",
  "streak.empty": "Start one today",
  "streak.unit": "days",
  "streak.avg": "Avg session",
  "streak.best": "Best day",
  "streak.minUnit": "min",
  "streak.bestEver": "Best",
  "streak.daysUnit": "days",
  "history.title": "Last 30 days",
  "history.total": "Total focused",
  "pack.add": "Add friend",
  "pack.placeholder": "Handle",
  "pack.online": "Online",
  "pack.offline": "Offline",
  "pack.leaderboard": "This week",
  "pack.refresh": "Refresh",
  "pack.empty": "No friends yet",
  "pack.emptyHint": "Add someone by their handle.",
  "pack.unknown": "Unknown",
  "pack.hours": "hrs",
  "blocks.identity": "Account",
  "blocks.telemetry": "Sessions",
  "blocks.uptime": "Time today",
  "blocks.boot": "Startup",
  "blocks.autostart": "Open at login",
  "blocks.autostartSub": "Lock-In starts with your PC so time is counted automatically.",
  "blocks.web": "Blocked sites",
  "blocks.sites": "Sites",
  "blocks.default": "Defaults",
  "blocks.custom": "Custom",
  "blocks.none": "No custom blocks",
  "blocks.remove": "Remove",
  "blocks.perm": "Always",
  "blocks.session": "Sessions",
  "blocks.addSite": "Add",
  "blocks.sitePlaceholder": "e.g. twitch.tv",
  "blocks.apps": "Blocked apps",
  "blocks.appPlaceholder": "e.g. discord.exe",
  "blocks.drop": "Drop an .exe here",
  "blocks.browse": "Choose from running apps",
  "blocks.clear": "Nothing blocked",
  "plan.calendar": "Google Calendar",
  "plan.schedule": "Schedule",
  "plan.disconnect": "Disconnect",
  "plan.connect": "Connect calendar",
  "plan.empty": "Empty",
  "plan.logPlaceholder": "Add a note",
  "login.subtitle": "Sign in to continue.",
  "login.protocol": "",
  "login.email": "Email",
  "login.password": "Password",
  "login.handle": "Handle",
  "login.submit": "Sign in",
  "login.register": "Create account",
  "login.toRegister": "New here? Create an account",
  "login.toLogin": "Already have an account? Sign in",
  "login.forgot": "Forgot your password?",
  "login.encrypted": "Encrypted",
  "login.protocolRegister": "Create your account.",
  "login.subtitleForgot": "Reset your password.",
  "login.protocolForgot": "We'll email you a reset link.",
  "login.sendReset": "Send reset link",
  "login.submitting": "Signing in…",
  "login.sending": "Sending…",
  "handle.submitting": "Saving…",
  "pack.syncing": "Refreshing…",
  "blocks.dropActive": "Drop to add",
  "watermark.left": null,
  "watermark.right": null,
  "handle.eyebrow": "",
  "handle.title": "Choose a handle",
  "handle.sub": "This is what other people see. It can't be changed later.",
  "handle.submit": "Confirm handle",
  "theme.title": "Theme",
};

/** Calm, full sentences that sit well in a serif. */
const botanical: Overrides = {
  "header.greeting": "Good {daypart}, {handle}",
  "header.sub": "{weekday} · a quiet place to get things done.",
  "stats.streak": "{streak}-day streak",
  "stats.tasks": "{open} tasks open",
  "stats.blocks": "{apps} apps · {sites} sites blocked",
  "dashboard.title": "",
  "plan.title": "Plan",
  "pack.title": "Friends",
  "blocks.title": "Blocked apps and sites",
  "uptime.label": "Focused today",
  "uptime.unit": "min",
  "signout": "Sign out",
  "offline.pill": "Offline — working locally",
  "session.active": "A session is running",
  "session.untitled": "Untitled",
  "nav.home": "Home",
  "nav.plan": "Plan",
  "nav.pack": "Friends",
  "nav.blocks": "Blocks",
  "mission.label": "This week's intention",
  "mission.placeholder": "What would make this week feel well spent?",
  "todo.label": "Tasks",
  "todo.count": "{done} of {total} complete",
  "todo.placeholder": "Add a task…",
  "todo.add": "Add",
  "todo.empty": "Nothing here yet. Add the first thing you'd like to do.",
  "session.label": "Begin a session",
  "session.running": "In progress",
  "session.target": "Working on {task}.",
  "session.untitledTarget": "something",
  "session.sub": "Distractions close themselves until the time is up.",
  "session.start": "Begin",
  "session.endsAt": "Ends at {time}",
  "preset.25": "Short",
  "preset.45": "Steady",
  "preset.60": "Deep",
  "preset.90": "Long",
  "preset.2": "Micro",
  "streak.label": "Streak",
  "streak.empty": "Begin one today to start counting.",
  "streak.unit": "days",
  "streak.avg": "Avg session",
  "streak.best": "Best day",
  "streak.minUnit": "min",
  "streak.bestEver": "Best",
  "streak.daysUnit": "days",
  "history.title": "The last thirty days",
  "history.total": "Total focused",
  "pack.add": "Add a friend",
  "pack.placeholder": "Their handle",
  "pack.online": "Here now",
  "pack.offline": "Away",
  "pack.leaderboard": "This week",
  "pack.refresh": "Refresh",
  "pack.empty": "No one here yet.",
  "pack.emptyHint": "Add a friend to share the quiet.",
  "pack.unknown": "Someone",
  "pack.hours": "hrs",
  "blocks.identity": "Your account",
  "blocks.telemetry": "Your sessions",
  "blocks.uptime": "Time today",
  "blocks.boot": "Startup",
  "blocks.autostart": "Open when my computer starts",
  "blocks.autostartSub":
    "Lock-In opens with your computer, so your time is counted without you thinking about it.",
  "blocks.web": "Blocked sites",
  "blocks.sites": "Sites",
  "blocks.default": "Common distractions",
  "blocks.custom": "Yours",
  "blocks.none": "You haven't added any yet.",
  "blocks.remove": "Remove",
  "blocks.perm": "Always",
  "blocks.session": "During sessions",
  "blocks.addSite": "Add",
  "blocks.sitePlaceholder": "e.g. twitch.tv",
  "blocks.apps": "Blocked apps",
  "blocks.appPlaceholder": "e.g. discord.exe",
  "blocks.drop": "Drop an .exe file here",
  "blocks.browse": "Choose from what's running",
  "blocks.clear": "Nothing is blocked.",
  "plan.calendar": "Google Calendar",
  "plan.schedule": "Your schedule",
  "plan.disconnect": "Disconnect",
  "plan.connect": "Connect your calendar",
  "plan.empty": "Nothing planned.",
  "plan.logPlaceholder": "Write something…",
  "login.subtitle": "Welcome back.",
  "login.protocol": "Sign in to pick up where you left off.",
  "login.email": "Email",
  "login.password": "Password",
  "login.handle": "Handle",
  "login.submit": "Sign in",
  "login.register": "Create account",
  "login.toRegister": "New here? Create an account.",
  "login.toLogin": "Already have an account? Sign in.",
  "login.forgot": "Forgotten your password?",
  "login.encrypted": "Encrypted",
  "login.protocolRegister": "Let's set up your account.",
  "login.subtitleForgot": "Let's get you back in.",
  "login.protocolForgot": "We'll send a reset link to your email.",
  "login.sendReset": "Send reset link",
  "login.submitting": "Signing in…",
  "login.sending": "Sending…",
  "handle.submitting": "Saving…",
  "pack.syncing": "Refreshing…",
  "blocks.dropActive": "Drop to add",
  "watermark.left": null,
  "watermark.right": null,
  "handle.eyebrow": "",
  "handle.title": "Choose a handle",
  "handle.sub": "This is the name others will see. It can't be changed later.",
  "handle.submit": "Confirm",
  "theme.title": "Appearance",
};

const TABLE: Record<ThemeName, Record<string, string | null>> = {
  operator,
  notebook: { ...operator, ...notebook },
  bento: { ...operator, ...bento },
  botanical: { ...operator, ...botanical },
};

export type CopyVars = Record<string, string | number>;

function fill(value: string, vars?: CopyVars): string {
  if (!vars) return value;
  return value.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
}

/** "morning" before noon, "afternoon" before 18:00, else "evening". */
export function daypart(now = new Date()): string {
  const h = now.getHours();
  return h < 12 ? "morning" : h < 18 ? "afternoon" : "evening";
}

export function weekday(now = new Date()): string {
  return now.toLocaleDateString(undefined, { weekday: "long" });
}

export function copyFor(theme: ThemeName, key: CopyKey, vars?: CopyVars): string | null {
  const value = TABLE[theme][key];
  // An empty string means the same as null: this theme renders nothing here.
  return value == null || value === "" ? null : fill(value, vars);
}

/**
 * t("dashboard.title") in the active theme's voice. Returns null for strings a
 * theme deliberately drops (Bento has no watermarks), so callers can render
 * nothing rather than an empty element.
 */
export function useCopy() {
  const { theme } = useTheme();
  return useCallback(
    (key: CopyKey, vars?: CopyVars) => copyFor(theme, key, vars),
    [theme]
  );
}

export { TABLE as COPY_TABLE };
